a = input('Digite algo...qualquer coisa: ')
print('O tipo primitivo do que você digitou é {}'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É Alfabético? {}'.format(a.isalpha()))
print('É Alfanúmérico? {}'.format(a.isalnum()))
print('Está em maiúscula? {}'.format(a.isupper()))
print('Está em minúscula? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
